### ISSUE TITLE
List of missing items from 9.2

### ISSUE THREAD

**Issue by peoii** [Zottelchen/adibags-shadowlands#14]
**Describe the bug**
Missing items from ZM 9.2, I don't have a complete list off the top of my head, but will list all the ones I have collected.

**Full Error Message**
```

Rare Proto Materials:
187879
187885
187889
187891
187892
187893
187894

Common Consumables:
187866
187867

Other:
187728
187908
187791
187790

Keys:
190197
```

**Comment by Zottelchen** [comment]
Hey, thanks for reporting! I've added these items to version 1.4.1.
