### ISSUE TITLE
Add tier crafting items

### ISSUE THREAD

**Issue by JH0Ni-github** [Zottelchen/adibags-shadowlands#15]
Shows as junk currently.

![Screenshot-2022-03-05-004304-Wow](https://user-images.githubusercontent.com/82328511/156852190-4dbb4bd8-740e-4fe0-9bc4-ae6a4cfa9109.png)

**Comment by Zottelchen** [comment]
Do u have an ID, name or Wowhead link? I cannot tell what that is as I currently am not actively playing.

**Comment by JH0Ni-github** [comment]
Late reply, sorry. This Wowhead page has all of them I think: https://www.wowhead.com/guides/sepulcher-first-ones-tier-set-overview-progenitor-acquisition-bonuses

**Comment by Zottelchen** [comment]
No worries! I've just pushed the new files, so update 1.4.3 will be available shortly everywhere. Thanks for reporting!
