### ISSUE TITLE
Crate of Anima-Infused Parts not sorting

### ISSUE THREAD

**Issue by jec324** [Zottelchen/adibags-shadowlands#17]
**Describe the bug**
Missing anima in section ... "Crate of Anima-Infused Parts" 

**To Reproduce**
(https://www.wowhead.com/item=188004/crate-of-anima-infused-parts) in bags and doesn't get sorted 
**Expected behavior**
Should be sorted into anima category

**Full Error Message**
No error
Put the error message in here!
No Error

**Comment by Zottelchen** [comment]
Hey, thanks for reporting! This issue is now resolved in 1.4.6 :)
