### ISSUE TITLE
Protoform Synthesis items to add

### ISSUE THREAD

**Issue by Pahonix** [Zottelchen/adibags-shadowlands#18]
**Is your feature request related to a problem? Please describe.**
Yes. A few items don't sort into the Protoform Synthesis section.

**Describe the solution you'd like**
Adding these itemIDs to the list will solve the problem.

**Describe alternatives you've considered**
No alternatives were considered.

**Additional context**
Here are the itemIDs of the missing items:

189158, -- Glimmer of Cunning
189167, -- Glimmer of Satisfaction
189171, -- Bauble of Pure Innovation
189175, -- Mawforged Bridle
189178, -- Tools of Incomprehensible Experimentation
189179, -- Unalloyed Bronze Ingot

**Comment by Zottelchen** [comment]
Hey, thanks for reporting! These items are now added in 1.4.7. Also, sorry, that I didn't notice your CurseForge comment before, my bad 😅

**Comment by Pahonix** [comment]
I honestly thought I was having a senior moment and thought that I had dreamt reporting those missing items since I couldn't find where I had posted a github issue on it. I forgot that I had just done it via the Curseforge comment, lol. Thanks for putting them in!
