### ISSUE TITLE
Missing enchants

### ISSUE THREAD

**Issue by cwwood0322** [Zottelchen/adibags-shadowlands#19]
**Describe the bug**
Not seeing enchants in bags if toon is not an enchanter.

**To Reproduce**
Unknown

**Expected behavior**
See what enchants you have in your bags without having to disable addon.
**Full Error Message**
none
Put the error message in here!
none

**Comment by Zottelchen** [comment]
I am not quite sure what you mean here. Which items specifically are not in the correct category? If you mean enchants as in enchanting scrolls, this addon does not touch those whatsoever.

**Comment by cwwood0322** [comment]
I noticed today that my Shadowlands enchants and I do mean the scrolls at least that is what the icon is are not showing up in my bags unless the toon is an enchanter. Like my DH has one enchant ring- tennet of haste in his bags right now but it is not displayed nor be searched for while adibags is enabled.

**Comment by Zottelchen** [comment]
This honestly sounds like an addon conflict, as this addon really does not touch those at all.
