### ISSUE TITLE
Improvement suggestion - Add category for items sold by Archivist Roh-Suir

### ISSUE THREAD

**Issue by talar13** [Zottelchen/adibags-shadowlands#3]
Similar to the functionality of items sold by Ve'nari except this would be items sold by Archivist Roh-Suir.  It would be the keys for the boxes used for Relic Level 2, The Teleporter Repair Kits, The Repaired Riftkey, etc.  I'm sure there are more items these are just the ones I have in my bag at the moment that are showing up in a weird spot.

**Comment by Zottelchen** [comment]
Hey, thanks for reporting! This is now a part of 1.2.10.
