### ISSUE TITLE
Suggestion : add localisation

### ISSUE THREAD

**Issue by ghost** [Zottelchen/adibags-shadowlands#4]
Hello,
Is it possible to add localisation file ? I can help to translate in French.
Thank you

**Comment by Zottelchen** [comment]
It is possible, but this requires some addon restructuring and may take a while.

**Comment by gjfLeo** [comment]
I can help with zhCN locale as well. It will be nice if supported. ^ ^

**Comment by Zottelchen** [comment]
@ghost @gjfLeo Thank you for your patience, at long last it is added. 😊
The easiest way to contribute is on Curseforge: https://www.curseforge.com/wow/addons/adibags-shadowlands/localization
